config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  devise_for :users
  resources :items do
    resources :reservations, only: [:new, :create]
  end
  get "reservations/", to: "reservations#index"
  get "myitemindex/", to: "items#itemindex"
  get "careers/", to: "pages#careers"
  get "about/", to: "pages#about"
  get "marco/", to: "pages#marco"
  root to: 'pages#home', as: "homepage"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, :description, :price, :category, presence: true
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :image_up, PhotoUploader
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :message
  validates :content, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer, :class_name => "User"
  belongs_to :host, :class_name => "User"
  has_many :messages
  validates :date_from, :date_to, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :own_reservations, :class_name => "Reservation", :foreign_key => "customer_id"
  has_many :received_reservations, :class_name => "Reservation", :foreign_key => "host_id"
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @items = Item.where(category: params[:category])
      @items_sorted = @items.near(params[:query], params[:radius].to_i)
    else
      @items = Item.all
    end


  @items = Item.where.not(latitude: nil, longitude: nil)

   @markers = @items_sorted.map do |item|
      {
      lat: item.latitude,
      lng: item.longitude,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
  end
end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    flash[:notice] = "You've successfully listed #{@item.title} on Tools for Life!"
    redirect_to myitemindex_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def itemindex
    @items = Item.where(user_id: current_user.id)
  end

  private

  def item_params
    params.require(:item).permit(:description, :price, :category, :address, :image_up, :user_id, :title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(host_id: current_user.id)
  end

  def new
    @item = Item.find(params[:item_id])
    @reservation = Reservation.new
  end

  def create
    @item = Item.find(params[:item_id])

    @reservation = Reservation.new(reservation_params)

    @reservation.host_id = @item.user_id
    @reservation.customer_id = current_user.id
    @reservation.item_id = @item.id

    if @reservation.save!
      flash[:notice] = "You've successfully booked #{@item.title}"
      redirect_to reservations_path
    else
      raise
    end

  end

  private
  def reservation_params
    params.require(:reservation).permit(:date_from, :date_to, :host_id, :item_id, :customer_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
 <div class="row-fluid">
  <div class="col-md-6">
    <div
  id="map"
  style="width: 100%;
  height: 100vh;"
  data-markers="<%= @markers.to_json %>"
></div>
  </div>
  <div class="col-md-6" >


    <% if @items_sorted.present? %>

    <% @items_sorted.each do |item| %>


    <div class="col-xs-12 col-sm-6">

      <%= link_to item_path(item) do %>

          <div class="card" style="border-radius: 3px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= item.photo %>);">
          <div class="card-category"> Available</div>
          <div class="card-description">
            <h2><%= item.title %></h2>
            <p>Very cool tool, the best</p>
            <p><%= item.price %></p>
          </div>
        </div>

      <% end %>
      </div>

    <% end %>

    <% else  %>
    <h3>Unfortunately, we couldn't find any items in your area</h3>
    <% end %>
  </div>
</div>

app/views/items/itemindex.html.erb
<div class="reservations">

  <h1>My tools</h1>

  <% @items.sort_by(&:created_at).reverse.each do |item|  %>

  <div class="row-fluid">

    <div class="col-xs-12 col-sm-4"">
      <div class="reservation tools">

        <%= link_to item_path(item) do %>
        <% if item.image_up.present? %>
        <div class="card reservation-image" style="border-radius: 3px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path item.image_up, crop: :fill %>');">
         <% else %>
         <div class="card reservation-image" style="border-radius: 3px; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= item.photo %>);">
          <% end %>
          <div class="card-category"> Available</div>
          <div class="card-description">
            <h2><%= item.title %></h2>
          </div>
        </div>
        <div class="reservation-card tools-card">
          <h5>Details:</h5>
          <ul>
            <li>Description: <%= item.description  %></li>
            <li>Category: <%= item.category  %></li>
            <li>Daily price: <%= item.price  %></li>
          </ul>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

app/views/items/new.html.erb
<% @category_array = ["Kitchen", "Garden", "Construction", "Painting", "Other"] %>

<div id="formwrapper">
<h1>Add new item</h1>
<%= simple_form_for @item do |f| %>
  <%= f.input :title, placeholder: 'Give your tool a title' %>
  <%= f.input :description, placeholder: 'Describe your tool' %>
  <%= f.input :price, placeholder: 'Specify the daily price of your tool' %>
  <%= f.input :category, collection: @category_array, as: :select %>
  <%= f.input :image_up %>
  <%= f.input :image_up_cache, as: :hidden %>

  <%= f.hidden_field :address, value: current_user.address %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add item", class: "btn btn-primary btn-submit" %>
<% end %>
</div>

 <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

app/views/items/show.html.erb
<div class="wrapping">

 <% if @item.image_up.present? %>
 <div class="card show-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @item.image_up%>')">
 </div>

 <% else %>

 <div class="card show-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= @item.photo %>')">
 </div>
 <% end %>
</div>





<div class="wrapper">
    <div class="booking-card-wrapper">
        <div class="booking-card-image">

          <% if @item.image_up.present? %>

          <%= cl_image_tag @item.image_up, class: "booking-card-image" %>



        <%else   %>

        <%= image_tag @item.photo, class: "booking-card-image" %>


        <%end  %>


        </div>
        <div class="booking-card-content">
            <div class="booking-card-description">
                <h1> <%= @item.title %></h1>
                <p> <%= @item.description %> </p>
            </div>
            <div class="booking-card-details">
                <div class="flex">
                    <div>
                        <span class="price"><%= @item.price %></span> €/day*
                        <div class="reviews">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <span class="amount">  28 reviews </span>
                        </div>
                    </div>
                    <div class="right-align">
                        <button class="btn-primary"><%= link_to "Book Now", new_item_reservation_path(@item) %></button>
                    </div>
                </div>
                <div>
                    <p class="side-note">* Prices may vary depending on selected date</p>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tools for life</title>
    <link rel="icon" href="../../assets/images/favicon-32x32.png" />
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
   <!-- <link href="css/bootstrap.min.css" rel="stylesheet">
   <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
   <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
   <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= render 'shared/footer' %>

   <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>


  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/efpasgdhao/image/upload/q_auto:eco/v1541236275/bigstock-set-of-tools-in-tool-box-on-a--51238249.jpg');">
  <div class="banner-content">
    <h1>Tools for Life</h1>
    <p>Available when it is needed</p>
    <a class="btn btn- btn-lg">Find your appliance</a>
  </div>
</div>

<%= form_tag items_path, method: :get do %>
 <div class="container">
  <div class="radio-tile-group">

    <div class="input-container">
      <input id="kitchen" class="radio-button" type="radio" name="category" value="kitchen" />
      <div class="radio-tile">
        <label for="walk" class="radio-tile-label">Kitchen</label>
      </div>
    </div>

    <div class="input-container">
      <input id="garden" class="radio-button" type="radio" name="category" value="garden" />
      <div class="radio-tile">
        <label for="bike" class="radio-tile-label">Garden</label>
      </div>
    </div>

    <div class="input-container">
      <input id="painting" class="radio-button" type="radio" name="category" value="Paiting" />
      <div class="radio-tile">
        <label for="drive" class="radio-tile-label">Painting</label>
      </div>
    </div>

    <div class="input-container">
      <input id="construction" class="radio-button" type="radio" name="category" value="construction" />
      <div class="radio-tile">
        <label for="fly" class="radio-tile-label">Construction</label>
      </div>
    </div>

    <div class="input-container">
      <input id="other" class="radio-button" type="radio" name="category" value="other" />
      <div class="radio-tile">
        <label for="fly" class="radio-tile-label">Other</label>
      </div>
    </div>

  </div>
</div>
  <br>
  <div id="input-fields">
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Please type in your address"
  %>
  <%= select_tag "radius", raw("<option>5</option><option>10</option><option>20</option><option>50</option><option>100</option>") %>
  </div>
  <%= submit_tag nil, class: "form_submit" %>
<% end %>

app/views/reservations/index.html.erb
<div class="reservations">

<h1>My reservations</h1>

<% @reservations.each do |reservation| %>
<% item = Item.find(reservation.item_id) %>

 <div class="row-fluid">

    <div class="col-xs-12 col-sm-4"">
      <div class="reservation">

      <%= link_to item_path(item) do %>

      <% if item.image_up.present? %>
      <div class="card reservation-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path item.image_up%>')">

      <% else %>
      <div class="card reservation-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= item.photo %>')">
      <% end %>
          <div class="card-category"> Available</div>
          <div class="card-description">
            <h2><%= item.title %></h2>
        </div>
          </div>
          <div class="reservation-card">
            <p>Reserved from: <%= reservation.date_from  %></p>
            <p>Reserved to: <%= reservation.date_to  %></p>
      </div>
      <% end %>
      </div>
      </div>
<% end %>
</div>

app/views/reservations/new.html.erb
<!--

<div style="width: 192px; margin: auto;">
<%= simple_form_for [@item, @reservation] do |f| %>
  <%= f.input :date_from %>
  <%= f.input :date_to %>
  <%= f.submit "add a reservation", class: "btn btn-primary" %>
<% end %>
</div>

 -->


<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Flatpickr Demo</h2>

    <%= simple_form_for [@item, @reservation] do |f| %>
      <%= f.input :date_from, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :date_to, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.submit "Add a reservation", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div id="footer" class="contact">
   <footer>

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#careers">Careers</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="/marco">See more of Marco</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

  </div>
  </div>







 <!-- Footer -->
 <!-- <footer class="page-footer font-small mdb-color darken-3 pt-4">

     Footer Elements
     <div class="container">

       Grid row
       <div class="row d-flex justify-content-center">

         Grid column
         <div class="col-md-6">

           Video

         </div>
         Grid column

       </div>
       Grid row

     </div>
     Footer Elements

     Copyright
     <div class="footer-copyright text-center py-3">© 2018 Copyright:
       <a href="https://mdbootstrap.com/bootstrap-tutorial/"> Lunic.com</a>
     </div>
     Copyright

   </footer>
   Footer
 -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to homepage_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://thumbs.dreamstime.com/z/service-tools-logo-illustration-art-isolated-background-56147331.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My tools", "/myitemindex", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My reservations", "/reservations", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add new tool", "/items/new/", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <!-- <img src="../../assets/images/user-solid.svg" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
          <i class="fas fa-user avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, action: :destroy do
               %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>